# Task 1

In [4]:
import numpy as np
rng = np.random.default_rng(seed=13)
readings = rng.normal (50,20,size = (360,4))

In [5]:
readings

array([[ 86.5351312 , -11.5666382 ,  69.16127951,  51.39274455],
       [ 76.36500048,  57.712585  ,  86.54517255,  50.63487518],
       [ 39.67541111,  61.60969843,  58.64213723,  42.86321285],
       ...,
       [ 46.77964872,  46.46571986,  84.19778004,  10.97571529],
       [ 38.35820852,  61.20212471,  38.22446261,   5.93845726],
       [ 61.26954779,  52.26031907,  31.99981642,  29.04392462]],
      shape=(360, 4))

In [7]:
readings.shape

(360, 4)

In [9]:
readings.dtype

dtype('float64')

In [11]:
readings[:3]

array([[ 86.5351312 , -11.5666382 ,  69.16127951,  51.39274455],
       [ 76.36500048,  57.712585  ,  86.54517255,  50.63487518],
       [ 39.67541111,  61.60969843,  58.64213723,  42.86321285]])

In [14]:
min_val = readings.min()
max_val = readings.max()
max_val

np.float64(130.3002031002495)

In [15]:
scaled_readings = (readings - min_val) / (max_val - min_val)
scaled_readings

array([[0.69150598, 0.        , 0.56904007, 0.4437921 ],
       [0.61981812, 0.48833979, 0.69157676, 0.43844998],
       [0.36119821, 0.51581001, 0.49489207, 0.38366859],
       ...,
       [0.41127501, 0.40906217, 0.67503031, 0.15889797],
       [0.35191343, 0.51293708, 0.35097067, 0.12339103],
       [0.51341233, 0.44990751, 0.30709399, 0.28625831]], shape=(360, 4))

In [16]:
column_means = readings.mean(axis=0)
column_means

array([50.65418279, 49.31695499, 51.80979665, 48.72065359])

In [17]:
centered_readings = readings - column_means
centered_readings

array([[ 35.88094841, -60.88359319,  17.35148285,   2.67209097],
       [ 25.7108177 ,   8.39563001,  34.7353759 ,   1.9142216 ],
       [-10.97877168,  12.29274344,   6.83234057,  -5.85744073],
       ...,
       [ -3.87453406,  -2.85123513,  32.38798338, -37.74493829],
       [-12.29597427,  11.88516972, -13.58533404, -42.78219632],
       [ 10.61536501,   2.94336408, -19.80998023, -19.67672896]],
      shape=(360, 4))

In [18]:
print("Original shape:", readings.shape)
print("Scaled shape:", scaled_readings.shape)
print("Centered shape:", centered_readings.shape)

Original shape: (360, 4)
Scaled shape: (360, 4)
Centered shape: (360, 4)


# Task 3

In [22]:
readings2 = (readings > 80) | (readings < 20)
readings2

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       ...,
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False, False, False]], shape=(360, 4))

In [23]:
readings2.sum()
#outliers count

np.int64(193)

In [29]:
readings2.sum()/readings.size*100
#13% outliers

np.float64(13.402777777777777)

In [32]:
cleaned_readings = readings.copy()

In [35]:
cleaned_readings[readings2]= np.nan

In [36]:
cleaned_readings

array([[        nan,         nan, 69.16127951, 51.39274455],
       [76.36500048, 57.712585  ,         nan, 50.63487518],
       [39.67541111, 61.60969843, 58.64213723, 42.86321285],
       ...,
       [46.77964872, 46.46571986,         nan,         nan],
       [38.35820852, 61.20212471, 38.22446261,         nan],
       [61.26954779, 52.26031907, 31.99981642, 29.04392462]],
      shape=(360, 4))

In [37]:
np_count= np.isnan(cleaned_readings).sum()

In [39]:
np_count
#np_count should be equal to readings2.sum()

np.int64(193)

# Task 4

In [44]:
sensor_mean=readings.mean(axis=0)
sensor_std = readings.std(axis=0)
sensor_std

array([19.73959893, 20.32904859, 19.5078079 , 19.85842525])

In [46]:
time_means = readings.mean(axis=1)
time_means.size

360

In [51]:
cleaned_readings_mean=np.nanmean(cleaned_readings, axis=0)
print("mean without outliers:",cleaned_readings_mean)
print("mean with outluiers:",readings.mean(axis=0))
#difference between mean with outliers and without outliets

mean without outliers: [50.40669098 50.33545248 50.8806329  49.06834037]
mean with outluiers: [50.65418279 49.31695499 51.80979665 48.72065359]


# Task 5

In [58]:
report = {"total_readings": readings.size,
          "outlier_count": readings2.sum(),
          "outlier_percent": readings2.sum()/readings.size*100,
          "sensor_means": sensor_mean.round(2) # for looking better
          ,
          "sensor_stds":sensor_std.round(2) #for looking better
}    

In [59]:
report

{'total_readings': 1440,
 'outlier_count': np.int64(193),
 'outlier_percent': np.float64(13.402777777777777),
 'sensor_means': array([50.65, 49.32, 51.81, 48.72]),
 'sensor_stds': array([19.74, 20.33, 19.51, 19.86])}

In [60]:
#Validation Report
if readings.size == report["total_readings"]:
    print("VALIDATION COMPLETED")

VALIDATION COMPLETED


In [61]:
report_message = f"""
--- SENSOR DATA REPORT ---
Total number of readings: {report['total_readings']}
Number of outliers identified: {report['outlier_count']}
Percentage of outliers: {report['outlier_percent']:.2f}%
Sensor Statistics:
Means: {report['sensor_means']}
Standard Deviations: {report['sensor_stds']}
--------------------------
"""

print(report_message)


--- SENSOR DATA REPORT ---
Total number of readings: 1440
Number of outliers identified: 193
Percentage of outliers: 13.40%
Sensor Statistics:
Means: [50.65 49.32 51.81 48.72]
Standard Deviations: [19.74 20.33 19.51 19.86]
--------------------------



# Task 6

In [69]:
import numpy as np
rng = np.random.default_rng(seed=13)
sim = rng.normal (0.0,1,size = (1000,6))

In [70]:
sim.shape

(1000, 6)

In [71]:
sim.dtype

dtype('float64')

In [72]:
sim[:3]

array([[ 1.82675656, -3.07833191,  0.95806398,  0.06963723,  1.31825002,
         0.38562925],
       [ 1.82725863,  0.03174376, -0.51622944,  0.58048492,  0.43210686,
        -0.35683936],
       [-0.24730382,  0.71944068,  0.70431599, -0.49393423, -0.36771372,
        -1.80679039]])

# Task 7

In [75]:
scenario_shift= np.array([-0.3, -0.1, 0.0, 0.1, 0.2, 0.4])
scenario_shift.shape

(6,)

In [76]:
adjusted_sim=sim + scenario_shift # sim's shape is (1000,6); scenario_shift's shape is (6,)

In [78]:
print("are their shapes same:", adjusted_sim.shape==sim.shape)

are their shapes same: True


In [79]:
print("original column means:", sim.mean(axis=0))
print("adjusted_sim means:", adjusted_sim.mean(axis=0))
print("mean difference:", adjusted_sim.mean(axis=0) - sim.mean(axis=0))

original column means: [ 0.04313753 -0.03892457  0.02006282 -0.00592867  0.04552659  0.01551258]
adjusted_sim means: [-0.25686247 -0.13892457  0.02006282  0.09407133  0.24552659  0.41551258]
mean difference: [-0.3 -0.1  0.   0.1  0.2  0.4]


# Task 8

In [82]:
scenario_means = adjusted_sim.mean(axis=0)
scenario_means

array([-0.25686247, -0.13892457,  0.02006282,  0.09407133,  0.24552659,
        0.41551258])

In [83]:
scenario_ranking = np.argsort(scenario_means)
scenario_ranking

array([0, 1, 2, 3, 4, 5])

In [85]:
partitioned_vals = np.partition(scenario_means, -2)
top_two_partition = partitioned_vals[-2:]
partitioned_vals
print("top2:", top_two_partition)

top2: [0.24552659 0.41551258]


In [86]:
full_sorted_vals = np.sort(scenario_means)
top_two_sorted = full_sorted_vals[-2:]
print("Top2(from full sort):", top_two_sorted)

Top2(from full sort): [0.24552659 0.41551258]


In [89]:
print("are They absolutely same?:",top_two_partition == top_two_sorted)

are They absolutely same?: [ True  True]


# Task 9

In [90]:
# using the same content
rng2 = np.random.default_rng(seed=13)
sim_2 = rng2.normal(0.0, 1, size=(1000, 6))

In [92]:
is_equal = np.array_equal(sim, sim_2)
print(f"sim and sim_2 are equal: {is_equal}")

sim and sim_2 are equal: True


In [93]:
# now use different seed
rng3 = np.random.default_rng(seed=42)
sim_3 = rng3.normal(0.0, 1, size=(1000, 6))

In [94]:
is_different = not np.allclose(sim, sim_3)
print(f"sim and sim_3 are different: {is_different}")

sim and sim_3 are different: True


In [95]:
# how many elements are same
matching_elements = np.sum(sim == sim_3)
print(f"Number of matching elements between sim and sim_3: {matching_elements}")

Number of matching elements between sim and sim_3: 0


# Task 10

In [97]:
report_sim = {
    "shape": adjusted_sim.shape,
    "scenario_means": scenario_means,
    "top_two_indices": scenario_ranking[-2:], # Ən yüksək 2 indeks
    "top_two_values": top_two_partition
}
report_sim

{'shape': (1000, 6),
 'scenario_means': array([-0.25686247, -0.13892457,  0.02006282,  0.09407133,  0.24552659,
         0.41551258]),
 'top_two_indices': array([4, 5]),
 'top_two_values': array([0.24552659, 0.41551258])}

In [98]:
#validton
is_valid = (len(report_sim["scenario_means"]) == 6 and 
            len(report_sim["top_two_indices"]) == 2)

In [99]:
if is_valid:
    report_text = f"""
    === SIMULATION FINAL REPORT ===
    Matrix Shape: {report_sim['shape']}
    Scenario Means: {report_sim['scenario_means'].round(4)} #for seein better result
    Top 2 Scenarios (Indices): {report_sim['top_two_indices']}
    Top 2 Performance Values: {report_sim['top_two_values'].round(4)}
    ===============================
    Validation Status: PASSED
    """
    print(report_text)
else:
    print("Validation Status: FAILED")


    === SIMULATION FINAL REPORT ===
    Matrix Shape: (1000, 6)
    Scenario Means: [-0.2569 -0.1389  0.0201  0.0941  0.2455  0.4155]
    Top 2 Scenarios (Indices): [4 5]
    Top 2 Performance Values: [0.2455 0.4155]
    Validation Status: PASSED
    
